# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zync < Formula
  desc "Kafka connector to sync Zed lakes to and from Kafka topics
"
  homepage "https://github.com/brimdata/zync"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/philrz/zync/releases/download/v1.0.0/zync-v1.0.0.darwin-amd64.tar.gz"
      sha256 "683e8ff33c8f65cd5cb127f9a5cb902a2fc04a661332432b0b967fcddef17afc"

      def install
        bin.install "zync"
      end
    end
    on_arm do
      url "https://github.com/philrz/zync/releases/download/v1.0.0/zync-v1.0.0.darwin-arm64.tar.gz"
      sha256 "f0d5ad573f3d16d352c2c22b1531cc31a4997f852d7b488b970ad9c7d0c91a1f"

      def install
        bin.install "zync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v1.0.0/zync-v1.0.0.linux-amd64.tar.gz"
        sha256 "a91cfb4d9bd36f894e49074589c6a8cf8e21fbc10e9dedc72f0f3adfec7b5f10"

        def install
          bin.install "zync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v1.0.0/zync-v1.0.0.linux-arm64.tar.gz"
        sha256 "c9125aa0a6e4f82cd46f2bfeccf08dd566189da1deaa947ee821e73ca7318432"

        def install
          bin.install "zync"
        end
      end
    end
  end
end
