# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zync < Formula
  desc "Kafka connector to sync Zed lakes to and from Kafka topics
"
  homepage "https://github.com/brimdata/zync"
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-v0.10.0.darwin-amd64.tar.gz"
      sha256 "9a9d1589f301d97681273bf8066d9f0b41f03825c118b83ec8115aaa5f3267a3"

      def install
        bin.install "zync"
      end
    end
    on_arm do
      url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-v0.10.0.darwin-arm64.tar.gz"
      sha256 "cf803cd3b4f2dd5a1816e3056fc2517ef78423fee34d48d055293311697d02a1"

      def install
        bin.install "zync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-v0.10.0.linux-amd64.tar.gz"
        sha256 "3a436ebcad0cdbad98e815a91684ae216a7537eae80b79afc2db90452c6fabca"

        def install
          bin.install "zync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-v0.10.0.linux-arm64.tar.gz"
        sha256 "23e8c8432478c3332002d6ce0c24cb7ad57fb8e8da53df301ee00e06e958f6c5"

        def install
          bin.install "zync"
        end
      end
    end
  end
end
