# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zync < Formula
  desc "Kafka connector to sync Zed lakes to and from Kafka topics
"
  homepage "https://github.com/brimdata/zync"
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-0.10.0.darwin-amd64.tar.gz"
      sha256 "0d1be66db110183c520a730094fafec7f0148a3c9c57e5aa4d63fba4bba34509"

      def install
        bin.install "zync"
      end
    end
    on_arm do
      url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-0.10.0.darwin-arm64.tar.gz"
      sha256 "31c92b0e7627570ccf97d7c43960a94969a10b1bb3e00b6ee1372c80600fd9ee"

      def install
        bin.install "zync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-0.10.0.linux-amd64.tar.gz"
        sha256 "2ac5d9f62c76fb2c31b5bd206f85cd94fe9d10aa68a253ccb63bd93483ce91b6"

        def install
          bin.install "zync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/philrz/zync/releases/download/v0.10.0/zync-0.10.0.linux-arm64.tar.gz"
        sha256 "307fd64e152f785a27365028b16a48e80f0d8049fa0f446c9713f4186549ff76"

        def install
          bin.install "zync"
        end
      end
    end
  end
end
