# This file was generated by GoReleaser. DO NOT EDIT.
cask "super" do
  version "0.18.0"

  on_macos do
    on_intel do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.darwin-amd64.tar.gz"
      sha256 "319214d4d23e6280a1248b1a8cce97e046782d8aa0339b1110253e73c4abf708"
    end
    on_arm do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.darwin-arm64.tar.gz"
      sha256 "c6ff09875475f5a1db2d4f6c2171f654b094f67a4af74189fcd9cc365b4c2f44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.linux-amd64.tar.gz"
      sha256 "fb6da842ea0b63def2d26a21a2f592aea31770f439f0370052c37d19408a92ae"
    end
    on_arm do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.linux-arm64.tar.gz"
      sha256 "2b2d008b71018a74c594b127b48cb44c8dcaad1bed200523c30342fe73bb9ab3"
    end
  end

  name "super"
  desc "An analytics database that fuses structured and semi-structured data"
  homepage "https://github.com/philrz/super"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super"

  # No zap stanza required

end
