# This file was generated by GoReleaser. DO NOT EDIT.
cask "super" do
  version "0.16.0"

  on_macos do
    on_intel do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.darwin-amd64.tar.gz"
      sha256 "6114515d717863e1400ce7987718aace341706b670436e781473f5329e64cc0f"
    end
    on_arm do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.darwin-arm64.tar.gz"
      sha256 "8a4b4e454d901f60c96dbbe3a190b338ebe08054c37b9fad3cbd77f95136d241"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.linux-amd64.tar.gz"
      sha256 "9758d9f8959efc59506b13637f7be841be5e03210972d33fa49d2dbe73a50dc8"
    end
    on_arm do
      url "https://github.com/philrz/super/releases/download/v#{version}/super-v#{version}.linux-arm64.tar.gz"
      sha256 "de31a37cf490a57ca24f55589d4e1719eb04c4c88f7677bb848f9fbdc1ae5a7f"
    end
  end

  name "super"
  desc "An analytics database that fuses structured and semi-structured data"
  homepage "https://github.com/philrz/super"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super"

  # No zap stanza required

end
