# This file was generated by GoReleaser. DO NOT EDIT.
cask "super" do
  name "super"
  desc "An analytics database that fuses structured and semi-structured data
"
  homepage "https://github.com/brimdata/super"
  version "710b432de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "super"

  on_macos do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-amd64.tar.gz"
      sha256 "2e8ca2cf8e2f311b790aaeaabe4575a111727d5c4f7cc65f09e50124f4917a57"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.darwin-arm64.tar.gz"
      sha256 "9904ddb7ac3d4fc6eeab4bf092d7ba2dc3651ae800071306a2dcfec665b627b5"
    end
  end

  on_linux do
    on_intel do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-amd64.tar.gz"
      sha256 "73898157b77f71bee7b4175128bbb3b71ad9449619bab7be199d90c9494aeeab"
    end
    on_arm do
      url "https://super-prereleases.s3.us-east-2.amazonaws.com/#{version}/super-#{version}.linux-arm64.tar.gz"
      sha256 "21b62982f561436273dfbf1c9d3a9bf175a0393e88becf380a778aab4e92684d"
    end
  end

  # No zap stanza required
end
