name: "Update SuperDB Homewbrew Cask"

on:
#  schedule:
#    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    
      - uses: actions/checkout@v4
        with:
          repository: philrz/super
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          path: super
      - name: Get current super main commit SHA
        id: current
        run: |
          cd super
          CURRENT_SHA=$(git rev-parse origin/main)
          echo "sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
      - name: Restore previous commit SHA
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .commit-sha
          key: main-commit-${{ steps.current.outputs.sha }}
          restore-keys: |
            main-commit-
      - name: Check if main has changed
        id: changed
        run: |
          if [ -f .commit-sha ]; then
            PREVIOUS_SHA=$(cat .commit-sha)
            if [ "$PREVIOUS_SHA" != "${{ steps.current.outputs.sha }}" ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/setup-go@v5
        with:
          go-version-file: super/go.mod
      - name: Build if changed
        if: steps.changed.outputs.changed == 'true'
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: super
          args: release --snapshot --clean
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: |
          sha_hash=${{ steps.current.outputs.sha }}
          short_hash=${sha_hash:0:9}
          for artifact in dist/super-${short_hash}*; do aws s3 cp $artifact s3://super-prereleases/${short_hash}/ ; done
      - run: |
          mkdir -p Casks
          cp super/dist/homebrew/Casks/super.rb Casks
          git config --global user.name 'Brim Automation'
          git config --global user.email 'automation@brimdata.com'
          git add Casks/super.rb
          git commit -am "update super Homebrew Cask to ${{ steps.checkout-ref.outputs.ref }}" || true
          git push
      - name: Save current commit SHA
        run: echo "${{ steps.current.outputs.sha }}" > .commit-sha
      - name: Save commit SHA cache
        uses: actions/cache/save@v4
        with:
          path: .commit-sha
          key: main-commit-${{ steps.current.outputs.sha }}
